# Generated by Django 4.1.2 on 2022-11-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_alter_message_receiver_delete_group_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=25)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.ManyToManyField(to='chatapp.groupchat')),
            ],
        ),
    ]
