# Generated by Django 4.1.2 on 2022-11-10 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_alter_groupdetails_group_name_alter_message_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdetails',
            name='group_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupmembers', to='chatapp.groupname'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='chatapp.groupdetails'),
        ),
    ]
