# Generated by Django 4.1.2 on 2022-11-16 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0014_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdetails',
            name='group_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupmembers', to='chatapp.groupname'),
        ),
    ]
