# Generated by Django 4.1.2 on 2022-11-18 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0015_alter_groupdetails_group_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='group',
        ),
        migrations.AlterField(
            model_name='groupdetails',
            name='group_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupname', to='chatapp.groupname'),
        ),
    ]
